## Customer segment using RFM analysis

## Data for RFM analysis
install.packages("tidyverse")
library(tidyverse)
library(dplyr)
library(ggplot2)

library(readr)
OrderData<-read_csv("~/sales_data_sample.csv ")

rfm_data<-OrderData %>%
  mutate(ORDERDATE=as.Date(ORDERDATE, "%m/%d/%Y")) %>%
  rename(customer_id=CUSTOMERNAME,
         order_date=ORDERDATE) %>%
  select(customer_id, order_date, SALES)

head(rfm_data)

unique(OrderData$CUSTOMERNAME)    #92

## RFM Score

rfm_table_score<-rfm_data %>%
  group_by(customer_id) %>%
  summarize(date_most_recent=max(order_date),
            transaction_count=n(),
            revenue=sum(SALES)) %>%
  mutate(analysis_date=as.Date("2005-6-30"),     
         recency_days=as.numeric(analysis_date-date_most_recent),
         R_Score=cut(recency_days,breaks=quantile(recency_days,probs=seq(0,1,by=0.2), names=FALSE),include.lowest=T, labels=5:1),
         F_Score=cut(transaction_count,breaks=quantile(transaction_count, probs=seq(0,1,by=0.2), names=FALSE),include.lowest=T,labels=1:5),
         M_Score=cut(revenue,breaks=quantile(revenue,probs=seq(0,1,by=0.2), names=FALSE),include.lowest=T,labels=1:5)
  ) %>%
  mutate(R_Score=as.numeric(as.character(R_Score)),
         F_Score=as.numeric(as.character(F_Score)),
         M_Score=as.numeric(as.character(M_Score)),
         RFM_Score=R_Score*100+F_Score*10+M_Score
  ) %>%
  arrange(desc(RFM_Score))

head(rfm_table_score)
tail(rfm_table_score)
summary(rfm_table_score)
## Customer segmantation 

rfm_table_score %>%
  count(customer_id) %>%
  arrange(desc(n))

seg_rfm<-within(rfm_table_score, {
  Segment=NA
  Segment[R_Score %in% c(4,5) & F_Score %in% c(4,5) & M_Score %in% c(4,5)]="Champions"
  Segment[R_Score %in% c(2:4) & F_Score %in% c(3:4) & M_Score %in% c(4:5)]="Loyal Customers"
  Segment[R_Score %in% c(3:5) & F_Score %in% c(1:3) & M_Score %in% c(1:3)]="Potential Loyalist"
  Segment[R_Score %in% c(4:5) & F_Score<2 & M_Score<2]="New Customers"
  Segment[R_Score %in% c(3:4) & F_Score<2 & M_Score<2]="Promising"
  Segment[R_Score %in% c(3:4) & F_Score %in% c(3:4) & M_Score %in% c(3:4)]="Need Attention"
  Segment[R_Score %in% c(2:3) & F_Score<3 & M_Score <3 ]="About To Sleep"
  Segment[R_Score <3 & F_Score %in% c(2:5) & M_Score %in% c(2:5) ]="At Risk"
  Segment[R_Score<2 & F_Score %in% c(4:5)  & M_Score %in% c(4:5) ]="Can't Lose Them"
  Segment[R_Score %in% c(2:3) & F_Score %in% c(2:3) & M_Score %in% c(2:3) ]="Hibernating"
  Segment[R_Score<2 & F_Score<2 & M_Score<2]="Lost"
}
)

head(seg_rfm)


# Segment Size 

seg_rfm %>%
  group_by(Segment) %>%
  count(Segment) %>%
  arrange(desc(n)) %>%
  rename(Count=n)


## Visualize median Recency, Frequency & Monetary value of customer segments

library(ggplot2)

# Median Recency by Segment

seg_rfm %>%
  group_by(Segment) %>%
  summarize(Median_R=mean(recency_days)) %>%
  ggplot(aes(x=Segment,y=Median_R))+
  geom_col()+
  coord_flip()+
  labs(title="Median Recency by Segment")

# Median Frequency by Segment
seg_rfm %>%
  group_by(Segment) %>%
  summarize(Median_F=mean(transaction_count)) %>%
  ggplot(aes(x=Segment,y=Median_F))+
  geom_col()+
  coord_flip()+
  labs(title="Median Frequency by Segment")

# Median Monetary by Segment
seg_rfm %>%
  group_by(Segment) %>%
  summarize(Median_M=mean(revenue)) %>%
  ggplot(aes(x=Segment,y=Median_M))+
  geom_col()+
  coord_flip()+
  labs(title="Median Monetary by Segment")

## Heat Map: the heat map shows the average monetary value for different categories of recency and frequency scores.

rfm_table_score %>%
  group_by(R_Score,F_Score)%>%
  summarise(Value=mean(revenue))%>%
  ungroup() %>%
  ggplot(aes(x=R_Score,y=F_Score))+
  geom_tile(aes(fill=Value),col="black")+
  geom_text(aes(label=round(Value)))+
  scale_fill_gradient(low="white",high="steelblue")+
  labs(fill="Mean Monetary Value")+
  theme(panel.background=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        legend.background = element_rect(fill = "gray96",colour = "gray88"),
        plot.background=element_rect(fill="gray99")
  )

## Bar Chart: 
# generate the distribution of frequency scores for the different combinations of monetary and recency scores
rfm_table_score %>%
  ggplot(aes(x=F_Score))+   
  geom_bar()+
  facet_grid(M_Score~R_Score)
  
  
  # generate the distribution of monetary scores for the different combinations of recency and frequency scores
  rfm_table_score %>%
  ggplot(aes(x=M_Score))+   
  geom_bar()+
  facet_grid(R_Score~F_Score)

## Histogram: examine the relative distribution of 
# monetary value (total revenue generated by each customer)
# recency days (days since the most recent visit for each customer)
# frequency (transaction count for each customer)

par(mfrow=c(1,3))

hist(rfm_table_score$revenue, main="Monetary",xlab="Monetary",ylab="Count",col="gray")
hist(rfm_table_score$recency_days, main="Recency", xlab="Recency",ylab="Count",col="gray")
hist(rfm_table_score$transaction_count, main="Frequency",xlab="Frequency",ylab="Count",col="gray")

## Customers by orders: visulaize the distribution of customers across orders

rfm_table_score %>%
  ggplot(aes(x=customer_id,y=transaction_count))+
  geom_col()+
  ylab("orders")+
  coord_flip()

## Scatter Plots
# The best customers are those who
# bought most recently
# most often
# and spend the most

# Let's examine the relationship between the above
# Recency vs Monetary Value

rfm_table_score %>%
  ggplot(aes(x=revenue,y=recency_days))+
  geom_point(alpha=0.4)+
  xlab("Monetary")+
  ylab("Recency")+
  ggtitle("Recency vs Monetary")

rfm_table_score %>%
  filter(revenue<250000) %>%
  ggplot(aes(x=revenue,y=recency_days))+
  geom_point(alpha=0.4)+
  xlab("Monetary")+
  ylab("Recency")+
  ggtitle("Recency vs Monetary")

# Frequency vs Monetary value

rfm_table_score %>% 
  ggplot(aes(x=revenue,y=transaction_count))+
  geom_point(alpha=0.2)+
  xlab("Monetary")+
  ylab("Frequency")+
  ggtitle("Frequency vs Monetary")

rfm_table_score %>%
  filter(revenue<250000) %>%
  ggplot(aes(x=revenue,y=transaction_count))+
  geom_point(alpha=0.4)+
  xlab("Monetary")+
  ylab("Frequency")+
  ggtitle("Frequency vs Monetary")

# There is linear relationship between Monetary and Frequency

# Recency vs Frequency

rfm_table_score %>%
  ggplot(aes(x=transaction_count,y=recency_days))+
  geom_point(alpha=0.4)+
  xlab("Frequency")+
  ylab("Recency")+
  ggtitle("Recency vs Frequency")

rfm_table_score %>%
  filter(transaction_count<100) %>%
  ggplot(aes(x=transaction_count,y=recency_days))+
  geom_point(alpha=0.4)+
  xlab("Frequency")+
  ylab("Recency")+
  ggtitle("Recency vs Frequency")
